import Head from "next/head";
import Header from "@/components/Header/Header";
import MainLayout from "@/layouts/MainLayout/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Page | Room Rent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <h1>Home Page</h1>
        </MainLayout>
      </main>
    </>
  );
}
