import { useEffect, useRef, useState } from "react";
import styles from "./index.module.scss";
import Head from "next/head";
import WithoutSearchLayout from "@/layouts/Default";
import { GoSearch } from "react-icons/go";
import ListYourProperty from "@/components/ListYourProperty/ListYourProperty";
import RecentlyListedRooms from "@/components/Rooms/RecentlyListedRooms";
import FullFurnishedRooms from "@/components/Rooms/FullFurnishedRooms";
import SemiFurnishedRooms from "@/components/Rooms/SemiFurnishedRooms";
import NoneFurnishedRooms from "@/components/Rooms/NoneFurnishedRooms";
import Testimonials from "@/components/Testimonials/Testimonials";

export default function Home(props) {
  const [ placeholder, setPlaceholder ] = useState("");
  const inputRef = useRef("");
  const [searchInput, setSearchInput] = useState("");
  function handleSearchSubmit() {
    console.log(searchInput);
  }

  const examplePhase = [
    "1BHK Apartment in Delhi",
    "1RHK room near me",
    "Studio room in Banglore",
  ]
  
  useEffect(()=>{
    // setInterval(() => {
    //   setPlaceholder(p=>p+1)
    // }, 1200)

    examplePhase.forEach((sentence, index)=>{
      [...sentence].forEach(char=>{
        setTimeout(() => {
          setPlaceholder(p=>p+char)
        }, 500);
      })
    })
    
    
  },[])
  return (
    <>
      <Head>
        <title>Home Page | Room Rent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithoutSearchLayout>
          <section className={styles["hero-section"]}>
            <div className="container m-auto">
              <h2 className="text-6xl text-center text-white font-bold my-14">Find Perfect Room for free</h2>
              <from className="flex w-1/2 m-auto rounded-md overflow-hidden" onSubmit={handleSearchSubmit}>
                <input
                  type="text"
                  ref={inputRef}
                  value={searchInput}
                  onChange={(e) => setSearchInput(e.target.value)}
                  placeholder={`Ex.  ${placeholder}`}
                  className="flex-1 px-5"
                />
                <button type="submit" onClick={handleSearchSubmit} className="bg-blue px-6 py-4 text-white font-medium">
                  {/* <GoSearch
                    size="35px"
                    className={styles["search-icon"]}
                    aria-label="search rooms"
                  /> */}
                  Search
                </button>
              </from>
            </div>
          </section>
          <RecentlyListedRooms/>
          <ListYourProperty/>
          <FullFurnishedRooms/>
          <SemiFurnishedRooms/>
          <NoneFurnishedRooms/>
          <Testimonials/>
        </WithoutSearchLayout>
      </main>
    </>
  );
}
//todo: qna