import { useRef, useState } from "react";
import styles from "./index.module.scss";
import Head from "next/head";
import WithoutSearchLayout from "@/layouts/WithoutSearchLayout/WithoutSearchLayout";
import { GoSearch } from "react-icons/go";
import ListYourProperty from "@/components/ListYourProperty/ListYourProperty";
import Rooms from "@/components/Rooms/Rooms";


export default function Home(props) {
  const inputRef = useRef("");
  const [searchInput, setSearchInput] = useState("");
  function handleSearchSubmit() {
    console.log(searchInput);
  }
  return (
    <>
      <Head>
        <title>Home Page | Room Rent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithoutSearchLayout>
          <section className={styles["hero-section"]}>
            <h2 className={styles["hero-section__title"]}>
              Find Perfect Room for free
            </h2>
            <from className={styles['search']} onSubmit={handleSearchSubmit}>
              <input
                type="text"
                ref={inputRef}
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                placeholder="Search..."
              />
              <button type="submit" onClick={handleSearchSubmit}>
                <GoSearch
                  size="35px"
                  className={styles["search-icon"]}
                />
              </button>
            </from>
          </section>
          <Rooms header="Recently Listed" rooms={props.recentRooms}/>
          <ListYourProperty/>
          <Rooms header="Full Furnished Rooms" rooms={props.fullFurnishedRooms}/>
          <Rooms header="Semi Furnished Rooms" rooms={props.semiFurnishedRooms}/>
          <Rooms header="None Furnished Rooms" rooms={props.noneFurnishedRooms}/>
        </WithoutSearchLayout>

      </main>
    </>
  );
}

//todo: testimonials
//todo: qna



export const getServerSideProps = async ({req, res}) => {
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59',
  );
  // fetch recent rooms
  const recentRoomsResponse = await fetch(`${process.env.API_BASE}/room/recent`);
  const recentRooms = await recentRoomsResponse.json();

  // fetch full furnished rooms
  const fullFurnishedRoomsResponse = await fetch(`${process.env.API_BASE}/room/full-furnished`)
  const fullFurnishedRooms = await fullFurnishedRoomsResponse.json();

  // fetch semi furnished rooms
  const semiFurnishedRoomsResponse = await fetch(`${process.env.API_BASE}/room/semi-furnished`)
  const semiFurnishedRooms = await semiFurnishedRoomsResponse.json();

  // fetch none furnished rooms
  const noneFurnishedRoomsResponse = await fetch(`${process.env.API_BASE}/room/none-furnished`)
  const noneFurnishedRooms = await noneFurnishedRoomsResponse.json();
  
  return { props: { recentRooms, fullFurnishedRooms, semiFurnishedRooms, noneFurnishedRooms } };
};